org: wilderemanuel
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::533894290576:role/LabRole

functions:
  scrape_table:
    handler: scrap_table.lambda_handler
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScrappingSismos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrappingSismos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
